# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserUID(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_id: str=None):  # noqa: E501
        """UserUID - a model defined in Swagger

        :param user_id: The user_id of this UserUID.  # noqa: E501
        :type user_id: str
        """
        self.swagger_types = {
            'user_id': str
        }

        self.attribute_map = {
            'user_id': 'user_id'
        }
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'UserUID':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserUID of this UserUID.  # noqa: E501
        :rtype: UserUID
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this UserUID.


        :return: The user_id of this UserUID.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this UserUID.


        :param user_id: The user_id of this UserUID.
        :type user_id: str
        """

        self._user_id = user_id
